language: ruby
cache: bundler
rvm:
  - 2.3.0
env:
  - DB=postgresql
addons:
  postgresql: 9.3
bundler_args: --without development
script:
  - export RAILS_ENV=test
  - bundle exec rake db:create db:migrate
  - bundle exec rspec spec
before_install:
  - sudo apt-get update && sudo apt-get install libicu-dev
  - cp config/database.travis.yml config/database.yml
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
