# Docs at https://github.com/mxabierto/adela/wiki/Docker#docker-compose
postgres:
  image: postgres
  volumes:
    - <ADELA-POSTGRES-VOLUME-PATH>:/var/lib/postgresql
  ports:
    - "5432"
redis:
  image: redis
  ports:
    - "6379"
sidekiq:
  build: .
  command: bundle exec sidekiq
  links:
    - postgres
    - redis
web:
  build: .
  environment:
    - HOST=''
    - MAILER_ADDRESS=''
    - MAILER_DOMAIN=''
    - MAILER_FROM=''
    - MAILER_PASSWORD=''
    - MAILER_USERNAME=''
    - REDIS_PORT_6379_TCP_ADDR=''
    - REDIS_PORT_6379_TCP_PORT=''
    - SECRET_KEY_BASE=''
    - SENDGRID_PASSWORD=''
    - SENDGRID_USERNAME=''
    - NEWRELIC_LICENSE_KEY=''
    - PORT=''
  ports:
    - "80:80"
  links:
    - postgres
    - redis
